-- ===================================================
-- CHẠY ĐOẠN SQL NÀY TRONG SUPABASE SQL EDITOR
-- ===================================================

-- 1. Tạo bảng lưu trữ ảnh
create table if not exists public.gallery_images (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  image_url text not null
);

-- 2. Bật bảo mật Row Level Security
alter table public.gallery_images enable row level security;

-- 3. Tạo Policy cho TABLE (Cho phép xem và thêm ảnh)
create policy "Allow Public View Images" 
on public.gallery_images for select 
using (true);

create policy "Allow Public Insert Images" 
on public.gallery_images for insert 
with check (true);

-- 4. Tạo Policy cho STORAGE (Cho phép upload file vào bucket 'gallery')
-- LƯU Ý: Bạn cần tạo bucket tên là 'gallery' và set Public trước trong menu Storage.

create policy "Allow Public Upload to Gallery Bucket"
on storage.objects for insert
with check ( bucket_id = 'gallery' );

create policy "Allow Public View Gallery Bucket"
on storage.objects for select
using ( bucket_id = 'gallery' );
