-- ===================================================
-- SCRIPT TẠO TÍNH NĂNG BÌNH LUẬN & THẢ TIM
-- Copy và chạy trong Supabase SQL Editor
-- ===================================================

-- 1. Bảng Bình Luận (Comments)
create table if not exists public.gallery_comments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  image_url text not null, -- Đường dẫn ảnh dùng làm ID định danh
  content text not null,
  author_name text default 'Người giấu tên'
);

-- 2. Bảng Cảm Xúc (Reactions - Thả tim, like...)
create table if not exists public.gallery_reactions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  image_url text not null,
  reaction_type text not null -- Ví dụ: '❤️', '👍', '😂'
);

-- 3. Bật RLS (Bảo mật)
alter table public.gallery_comments enable row level security;
alter table public.gallery_reactions enable row level security;

-- 4. Policy (Cho phép ai cũng xem và đăng)
create policy "Public view comments" on public.gallery_comments for select using (true);
create policy "Public post comments" on public.gallery_comments for insert with check (true);

create policy "Public view reactions" on public.gallery_reactions for select using (true);
create policy "Public post reactions" on public.gallery_reactions for insert with check (true);
