
-- ===================================================
-- SCRIPT TẠO TÍNH NĂNG GÓC HỐI TIẾC (ẨN DANH)
-- Copy và chạy trong Supabase SQL Editor
-- ===================================================

-- 1. Bảng Hối Tiếc (Regrets)
create table if not exists public.regrets (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  content text not null
);

-- 2. Enable RLS
alter table public.regrets enable row level security;

-- 3. Policies (Cho phép ai cũng xem và đăng, không cần authen)
create policy "Public view regrets" on public.regrets for select using (true);
create policy "Public insert regrets" on public.regrets for insert with check (true);
