
-- ===================================================
-- SCRIPT TẠO BẢNG KẾT QUẢ TRẢ LỜI CÂU HỎI
-- Copy và chạy trong Supabase SQL Editor
-- ===================================================

-- 1. Create table
create table if not exists public.quiz_results (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  score integer default 0,
  total_questions integer default 0
);

-- 2. Enable RLS
alter table public.quiz_results enable row level security;

-- 3. Policies
create policy "Public view quiz results" on public.quiz_results for select using (true);
create policy "Public insert quiz results" on public.quiz_results for insert with check (true);
