-- Create table to store visit logs
create table if not exists visit_logs (
  id bigint generated by default as identity primary key,
  ip_address text,
  city text,
  country text,
  region text,
  latitude float,
  longitude float,
  isp text,
  user_agent text,
  device_type text, -- 'Mobile' or 'Desktop'
  visited_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS
alter table visit_logs enable row level security;

-- Setup policies
-- Allow anyone (anon) to insert logs
create policy "Enable insert for anon" 
  on visit_logs for insert 
  with check (true);

-- Allow everyone to view logs (or restrict this if you want privacy)
create policy "Enable read access for all"
  on visit_logs for select
  using (true);
